import { Button, Flex, Hide, Show, Spinner, Text } from "@chakra-ui/react";
import SideBar from "../SideBar";
import { type ReactNode } from "react";
import { signIn, useSession } from "next-auth/react";
import Logo from "../Logo";
import Head from "next/head";
import Header from "../Header";

const Login = () => {
  return (
    <Flex direction="column" align="center" justify="center" flex="1">
      <Logo />
      <Text fontSize={24} mt={4}>
        Humanage
      </Text>
      <Text mt={2} color="gray">
        You manage humans
      </Text>
      <Button colorScheme="purple" onClick={() => void signIn()} mt={8}>
        Log in
      </Button>
    </Flex>
  );
};

const Loading = () => {
  return (
    <Flex direction="column" align="center" justify="center" flex="1">
      <Spinner size="xl" />
    </Flex>
  );
};

const HomeLayout = ({ children }: { children: ReactNode }) => {
  const { data: session, status } = useSession();
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex w="full" minH="100vh" justify="center">
        <Flex maxW="container.xl" w="full">
          {status === "loading" ? (
            <Loading />
          ) : !session ? (
            <Login />
          ) : (
            <>
              <Show above="lg">
                <SideBar pos="sticky" top={0} h="100vh" />
              </Show>
              <Flex direction="column" w="full">
                <Hide above="lg">
                  <Header />
                </Hide>
                <Flex direction="column" w="full" p={4} ps={{ lg: 8 }}>
                  {children}
                </Flex>
              </Flex>
            </>
          )}
        </Flex>
      </Flex>
    </>
  );
};

export default HomeLayout;
