import { Button, Flex, Hide, Show, Text } from "@chakra-ui/react";
import SideBar from "../SideBar";
import { type ReactNode } from "react";
import { signIn, useSession } from "next-auth/react";
import Logo from "../Logo";
import Head from "next/head";
import Header from "../Header";

const Login = () => {
  return (
    <Flex direction="column" align="center" justify="center" flex="1">
      <Logo />
      <Text fontSize={24} mt={4}>
        Humanage
      </Text>
      <Text mt={2} color="gray">
        You manage humans
      </Text>
      <Button colorScheme="purple" onClick={() => void signIn()} mt={8}>
        Log in
      </Button>
    </Flex>
  );
};

const HomeLayout = ({ children }: { children: ReactNode }) => {
  const { data: session } = useSession();
  return (
    <>
      <Head>
        <title>HUMG 👻</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex w="full" minH="100vh" justify="center">
        <Flex
          maxW="container.xl"
          w="full"
          borderWidth={2}
          borderColor="red"
          borderStyle="dashed"
        >
          {!session ? (
            <Login />
          ) : (
            <>
              <Show above="lg">
                <SideBar />
              </Show>
              <Flex direction="column" w="full" p={4}>
                <Hide above="lg">
                  <Header />
                </Hide>
                {children}
              </Flex>
            </>
          )}
        </Flex>
      </Flex>
    </>
  );
};

export default HomeLayout;
