import Head from "next/head";
import { api } from "@/utils/api";
import { Flex, Text } from "@chakra-ui/react";
import { type NextPageWithLayout } from "./_app";
import { type ReactElement } from "react";
import HomeLayout from "@/components/layout/HomeLayout";

const Home: NextPageWithLayout = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>HUMG 👻</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex flex={1} bg="red">
        <Text>
          {hello.data ? hello.data.greeting : "Loading tRPC query..."}
        </Text>
      </Flex>
    </>
  );
};

Home.getLayout = (page: ReactElement) => {
  return <HomeLayout>{page}</HomeLayout>;
};

export default Home;
