import Head from "next/head";
import { api } from "@/utils/api";
import { Flex, Text } from "@chakra-ui/react";
import SideBar from "@/components/SideBar";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>HUMG 👻</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex minH="100vh" justify="center">
        <Flex maxW="container.xl" flex="1" borderWidth={1} borderColor="red">
          <SideBar />
          <Flex flex="1" bg="gray">
            <Text>
              {hello.data ? hello.data.greeting : "Loading tRPC query..."}
            </Text>
          </Flex>
        </Flex>
      </Flex>
    </>
  );
}
