import Head from "next/head";
import { Flex, Text } from "@chakra-ui/react";

const Projects = () => {
  return (
    <>
      <Head>
        <title>HUMG 👻</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex flex={1}>
        <Text>Projects</Text>
      </Flex>
    </>
  );
};

export default Projects;
